CREATE TABLE IF NOT EXISTS `glamira_raw.summary_raw`
(
    _id JSON,
    time_stamp STRING,
    ip STRING,
    user_agent STRING,
    resolution STRING,
    user_id_db STRING,
    device_id STRING,
    api_version STRING,
    store_id STRING,
    local_time STRING,
    show_recommendation BOOLEAN,
    current_url STRING,
    referrer_url STRING,
    email_address STRING,
    recommendation BOOLEAN,
    utm_source STRING,
    collection STRING,
    product_id STRING,
    viewing_product_id STRING,
    cat_id STRING,
    collect_id STRING,
    option ARRAY<STRUCT<
        option_label STRING,
        option_id STRING,
        value_label STRING,
        value_id STRING,
        quality STRING,
        quality_label STRING,
        alloy STRING,
        diamond STRING,
        shapediamond STRING,
        stone STRING,
        pearlcolor STRING,
        finish STRING,
        price STRING,
        category_id STRING,
        `category id` STRING,
        kollektion STRING,
        kollektion_id STRING
    >>,
    order_id STRING,
    recommendation_product_id STRING,
    recommendation_clicked_position STRING,
    utm_medium STRING,
    key_search STRING,
    price STRING,
    currency STRING,
    recommendation_product_position INT64,
    is_paypal BOOLEAN,
    cart_products ARRAY<STRUCT<
        product_id STRING,
        price STRING,
        currency STRING,
        amount INT64,
        option ARRAY<STRUCT<
            option_id STRING,
            option_label STRING,
            value_id STRING,
            value_label STRING
        >>
    >>
);
